# Generated by Django 4.1.6 on 2023-02-05 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detalle', models.CharField(max_length=200)),
                ('ncomprobante', models.CharField(max_length=200)),
                ('eingresos', models.FloatField()),
                ('eegresos', models.FloatField()),
                ('esaldo', models.FloatField()),
                ('bingresos', models.FloatField()),
                ('begresos', models.FloatField()),
                ('bsaldo', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
