# Generated by Django 4.1.6 on 2023-02-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='begresos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='bingresos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='bsaldo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='eegresos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='eingresos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='esaldo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
