# Generated by Django 4.1.6 on 2023-02-06 16:43

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_registro_tipo_remove_registro_tipo_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='btotalegresos',
            field=models.FloatField(blank=True, null=True, validators=[app.models.validate_even]),
        ),
        migrations.AddField(
            model_name='registro',
            name='btotalingresos',
            field=models.FloatField(blank=True, null=True, validators=[app.models.validate_even]),
        ),
        migrations.AddField(
            model_name='registro',
            name='etotalegresos',
            field=models.FloatField(blank=True, null=True, validators=[app.models.validate_even]),
        ),
        migrations.AddField(
            model_name='registro',
            name='etotalingresos',
            field=models.FloatField(blank=True, null=True, validators=[app.models.validate_even]),
        ),
    ]
